name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Nix
      uses: DeterminateSystems/nix-installer-action@main
      
    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
      
    - name: Run tests
      run: |
        cd tests
        nix run .#test
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: tests/results/
        
    - name: Run Rust tests
      run: |
        cargo test --verbose
        
    - name: Build release
      run: |
        cargo build --release
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nexo-release
        path: target/release/nexo 